//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qa_regressao.Config {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PathArqIniCaixa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PathArqIniCaixa() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("qa_regressao.Config.PathArqIniCaixa", typeof(PathArqIniCaixa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1.
        /// </summary>
        internal static string AcbrSat {
            get {
                return ResourceManager.GetString("AcbrSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\AltecTeste\Altec Caixa\Caixa.ini.
        /// </summary>
        internal static string ArqIniCaixa {
            get {
                return ResourceManager.GetString("ArqIniCaixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DELIVERY_REGRESSAO_LOJA.
        /// </summary>
        internal static string BancoDeDados {
            get {
                return ResourceManager.GetString("BancoDeDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 123456789.
        /// </summary>
        internal static string Cod_Ativacao {
            get {
                return ResourceManager.GetString("Cod_Ativacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1.
        /// </summary>
        internal static string Modelo_Imp {
            get {
                return ResourceManager.GetString("Modelo_Imp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\AltecTeste\Altec Caixa\Diversos\Arquivos SAT.
        /// </summary>
        internal static string Pasta_Arquivo {
            get {
                return ResourceManager.GetString("Pasta_Arquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 8513.
        /// </summary>
        internal static string Porta {
            get {
                return ResourceManager.GetString("Porta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a \\SERVER-QA\BAR.
        /// </summary>
        internal static string PortaImpSat {
            get {
                return ResourceManager.GetString("PortaImpSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 123456789.
        /// </summary>
        internal static string Serie_Equipamento {
            get {
                return ResourceManager.GetString("Serie_Equipamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Localhost.
        /// </summary>
        internal static string Servidor {
            get {
                return ResourceManager.GetString("Servidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SGR-SAT SISTEMA DE GESTAO E RETAGUARDA DO SAT.
        /// </summary>
        internal static string Signac {
            get {
                return ResourceManager.GetString("Signac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0.
        /// </summary>
        internal static string Use_Sat {
            get {
                return ResourceManager.GetString("Use_Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string Velocidade_Sat {
            get {
                return ResourceManager.GetString("Velocidade_Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0,08.
        /// </summary>
        internal static string Versao_Layout {
            get {
                return ResourceManager.GetString("Versao_Layout", resourceCulture);
            }
        }
    }
}
