//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qa_regressao.Config {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PathCaminhoExe {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PathCaminhoExe() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("qa_regressao.Config.PathCaminhoExe", typeof(PathCaminhoExe).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Antena.
        /// </summary>
        internal static string ExecutavelAntena {
            get {
                return ResourceManager.GetString("ExecutavelAntena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Caixa.exe.
        /// </summary>
        internal static string ExecutavelCaixa {
            get {
                return ResourceManager.GetString("ExecutavelCaixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CaixaTouch.exe.
        /// </summary>
        internal static string ExecutavelCaixaTouch {
            get {
                return ResourceManager.GetString("ExecutavelCaixaTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DeliveryWeb.
        /// </summary>
        internal static string ExecutavelDeliveryWeb {
            get {
                return ResourceManager.GetString("ExecutavelDeliveryWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerencial.exe.
        /// </summary>
        internal static string ExecutavelGerencial {
            get {
                return ResourceManager.GetString("ExecutavelGerencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estoque.exe.
        /// </summary>
        internal static string ExecutavelRetaguarda {
            get {
                return ResourceManager.GetString("ExecutavelRetaguarda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Emulador SAT-CFe.jar.
        /// </summary>
        internal static string ExecutavelSAT {
            get {
                return ResourceManager.GetString("ExecutavelSAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SitDemo.exe.
        /// </summary>
        internal static string ExecutavelSiTef {
            get {
                return ResourceManager.GetString("ExecutavelSiTef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\Altec\Altec Antena\.
        /// </summary>
        internal static string PathAntena {
            get {
                return ResourceManager.GetString("PathAntena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\Altec\Altec Caixa\.
        /// </summary>
        internal static string PathCaixa {
            get {
                return ResourceManager.GetString("PathCaixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\Altec\Altec Caixa Touch\.
        /// </summary>
        internal static string PathCaixaTouch {
            get {
                return ResourceManager.GetString("PathCaixaTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\Altec\DeliveryWeb\.
        /// </summary>
        internal static string PathDeliveryWeb {
            get {
                return ResourceManager.GetString("PathDeliveryWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\Program Files (x86)\SAT-CFe\Emulador\.
        /// </summary>
        internal static string PathEmuladorSAT {
            get {
                return ResourceManager.GetString("PathEmuladorSAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\Altec\Altec Gerencial\.
        /// </summary>
        internal static string PathGerencial {
            get {
                return ResourceManager.GetString("PathGerencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\Altec\Altec Retaguarda.
        /// </summary>
        internal static string PathRetaguarda {
            get {
                return ResourceManager.GetString("PathRetaguarda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a C:\SiTef\APLIC.WIN.
        /// </summary>
        internal static string PathSiTef {
            get {
                return ResourceManager.GetString("PathSiTef", resourceCulture);
            }
        }
    }
}
